name: bcall
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-15.0.dev <4.0.0'

dependencies:
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  flutter_svg: ^1.1.6
  flutter_webrtc: ^0.9.45
  google_fonts: ^6.1.0
  http: ^1.1.0
  iconify_flutter: ^0.0.5
  majesticons_flutter: ^0.0.1
  overlapping_panels: ^0.0.3
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    -  assets/icons/


